### ISSUE TITLE
Fix Travis test invocation

### ISSUE THREAD

**Issue by JIoJIaJIu** [nodejs-tensorflow/nodejs-tensorflow#34]
```bash
> mocha-webpack --colors --webpack-config tools/webpack.config.test.js --full-trace "test/**/*.js"
ERROR in ./.tmp/mocha-webpack/a05ebb408121f5c2c4489e37cb94fa2c-entry.js
Module build failed: TypeError: fileSystem.statSync is not a function at module.exports (/home/travis/build/nodejs-tensorflow/nodejs-tensorflow/node_modules/babel-loader/lib/utils/exists.js:7:25) at find (/home/travis/build/nodejs-tensorflow/nodejs-tensorflow/node_modules/babel-loader/lib/resolve-rc.js:13:9)  at Object.module.exports (/home/travis/build/nodejs-tensorflow/nodejs-tensorflow/node_modules/babel-loader/lib/index.js:113:132)
npm ERR! Test failed.  See above for more details.
```

**Comment by JIoJIaJIu** [comment]
`IN PROGRESS`

**Comment by JIoJIaJIu** [comment]
`DONE`
